#!/usr/bin/env python3
"""Convert a video into src/video_data.h (raw LZMA1 stream).

Usage:
    python3 tools/convert.py video.mp4 [--fps 20] [--width 64] [--height 36]
                                       [--threshold 128] [--out src/video_data.h]

Differences from the original converter:
  * emits a *raw* LZMA1 stream (no .xz container, no CRC64, no index/footer)
  * tunes lc=1 lp=0 pb=0, which suits packed 1bpp frames better than the
    defaults (lc=3 pb=2)
  * writes LF line endings and 24 bytes per line

Things that were measured and rejected (all made the output *bigger*, because
LZMA already matches whole previous frames across its 64 MB dictionary):
    XOR inter-frame delta  ->  +37%
    per-frame dedup+index  ->   +3%
    bit run-length coding  ->  +11%
    row-diff flags+payload ->   +6%
    column-major transpose ->   +9%
"""
import argparse
import lzma
import os
import sys

import numpy as np

try:
    import cv2
except ImportError:
    sys.exit("ERROR: pip install opencv-python numpy")

LC, LP, PB = 1, 0, 0
FILTERS = [{"id": lzma.FILTER_LZMA1,
            "preset": 9 | lzma.PRESET_EXTREME,
            "lc": LC, "lp": LP, "pb": PB}]


def pack_bits(arr2d):
    return np.packbits(arr2d.reshape(-1), bitorder="little").tobytes()


def write_header(path, w, h, fps, frames, bpf, blob):
    with open(path, "w", newline="\n") as f:
        f.write("/* generated by tools/convert.py - do not edit */\n"
                "#pragma once\n\n")
        f.write("#define VID_WIDTH       %d\n" % w)
        f.write("#define VID_HEIGHT      %d\n" % h)
        f.write("#define VID_FPS         %d\n" % fps)
        f.write("#define VID_FRAMES      %d\n" % frames)
        f.write("#define VID_FRAME_BYTES %d\n" % bpf)
        f.write("#define VID_DATA_SIZE   %d\n\n" % len(blob))
        f.write("/* raw LZMA1 stream: lc=%d lp=%d pb=%d, no container, "
                "no end marker */\n" % (LC, LP, PB))
        f.write("#define VID_LZMA_LC     %d\n" % LC)
        f.write("#define VID_LZMA_LP     %d\n" % LP)
        f.write("#define VID_LZMA_PB     %d\n\n" % PB)
        f.write("static const unsigned char video_data[VID_DATA_SIZE] = {\n")
        for i in range(0, len(blob), 24):
            f.write(",".join("0x%02X" % b for b in blob[i:i + 24]) + ",\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("video")
    ap.add_argument("--width", type=int, default=64)
    ap.add_argument("--height", type=int, default=36)
    ap.add_argument("--fps", type=int, default=20)
    ap.add_argument("--threshold", type=int, default=128)
    ap.add_argument("--max-frames", type=int, default=0)
    ap.add_argument("--out", default="src/video_data.h")
    ap.add_argument("--bin", default="")
    a = ap.parse_args()

    cap = cv2.VideoCapture(a.video)
    if not cap.isOpened():
        sys.exit("Cannot open: %s" % a.video)

    src_fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    step = max(1, int(round(src_fps / a.fps)))
    bpf = (a.width * a.height + 7) // 8
    print("source fps=%.1f  step=%d  output ~%d fps  %d B/frame"
          % (src_fps, step, a.fps, bpf))

    frames = []
    ri = 0
    while True:
        ok, img = cap.read()
        if not ok:
            break
        if ri % step == 0:
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            small = cv2.resize(gray, (a.width, a.height),
                               interpolation=cv2.INTER_AREA)
            _, bw = cv2.threshold(small, a.threshold, 1, cv2.THRESH_BINARY)
            frames.append(pack_bits(bw.astype(np.uint8)))
            if a.max_frames and len(frames) >= a.max_frames:
                break
        ri += 1
    cap.release()

    stream = b"".join(frames)
    print("frames: %d   raw stream: %d B" % (len(frames), len(stream)))

    blob = lzma.compress(stream, format=lzma.FORMAT_RAW, filters=FILTERS)
    print("compressed: %d B  (%.1f%% of raw)"
          % (len(blob), 100.0 * len(blob) / len(stream)))

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    write_header(a.out, a.width, a.height, a.fps, len(frames), bpf, blob)
    if a.bin:
        open(a.bin, "wb").write(blob)
    print("wrote %s" % a.out)


if __name__ == "__main__":
    main()
