#!/usr/bin/env python3
"""Re-encode an existing video_data.h into the new raw-LZMA1 format.

Usage:
    python3 tools/reencode.py <old_video_data.h> [--fps N] [--out src/video_data.h]

The old header stores an .xz container (header + CRC64 + index + footer).
We unpack it and re-emit a raw LZMA1 stream with lc=1 lp=0 pb=0, which is
smaller and needs only a ~2 KB decoder instead of liblzma.
"""
import argparse
import lzma
import re
import sys

LC, LP, PB = 1, 0, 0
FILTERS = [{"id": lzma.FILTER_LZMA1,
            "preset": 9 | lzma.PRESET_EXTREME,
            "lc": LC, "lp": LP, "pb": PB}]


def parse_old_header(path):
    src = open(path, "rb").read().decode("latin1")

    def d(name):
        m = re.search(r"#define\s+%s\s+(\d+)" % name, src)
        if not m:
            sys.exit("missing #define %s in %s" % (name, path))
        return int(m.group(1))

    def opt(name):
        m = re.search(r"#define\s+%s\s+(\d+)" % name, src)
        return int(m.group(1)) if m else None

    w, h, fps, frames, bpf = (d("VID_WIDTH"), d("VID_HEIGHT"), d("VID_FPS"),
                              d("VID_FRAMES"), d("VID_FRAME_BYTES"))
    body = src.split("video_data[VID_DATA_SIZE] = {", 1)[1]
    blob = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", body))

    # Two input flavours are accepted, so this script can be re-run on its own
    # output (e.g. to drop fps a second time):
    #   - the original project's header, which holds an .xz container
    #   - a header we generated, which holds a raw LZMA1 stream and therefore
    #     carries VID_LZMA_LC/LP/PB defines describing how to decode it
    lc, lp, pb = opt("VID_LZMA_LC"), opt("VID_LZMA_LP"), opt("VID_LZMA_PB")
    if lc is None:
        raw = lzma.decompress(blob)
    else:
        dec = lzma.LZMADecompressor(
            format=lzma.FORMAT_RAW,
            filters=[{"id": lzma.FILTER_LZMA1, "lc": lc, "lp": lp, "pb": pb}])
        raw = dec.decompress(blob)
    if len(raw) != frames * bpf:
        sys.exit("unexpected payload: %d != %d" % (len(raw), frames * bpf))
    return w, h, fps, frames, bpf, raw, len(blob)


def drop_fps(raw, bpf, frames, src_fps, dst_fps):
    if dst_fps >= src_fps:
        return raw, frames, src_fps
    step = src_fps / float(dst_fps)
    keep = []
    i = 0.0
    while int(round(i)) < frames:
        keep.append(int(round(i)))
        i += step
    out = b"".join(raw[k * bpf:(k + 1) * bpf] for k in keep)
    return out, len(keep), dst_fps


def write_header(path, w, h, fps, frames, bpf, blob):
    with open(path, "w", newline="\n") as f:
        f.write("/* generated by tools/reencode.py - do not edit */\n"
                "#pragma once\n\n")
        f.write("#define VID_WIDTH       %d\n" % w)
        f.write("#define VID_HEIGHT      %d\n" % h)
        f.write("#define VID_FPS         %d\n" % fps)
        f.write("#define VID_FRAMES      %d\n" % frames)
        f.write("#define VID_FRAME_BYTES %d\n" % bpf)
        f.write("#define VID_DATA_SIZE   %d\n\n" % len(blob))
        f.write("/* raw LZMA1 stream: lc=%d lp=%d pb=%d, no container, no end marker */\n"
                % (LC, LP, PB))
        f.write("#define VID_LZMA_LC     %d\n" % LC)
        f.write("#define VID_LZMA_LP     %d\n" % LP)
        f.write("#define VID_LZMA_PB     %d\n\n" % PB)
        f.write("static const unsigned char video_data[VID_DATA_SIZE] = {\n")
        for i in range(0, len(blob), 24):
            f.write("" + ",".join("0x%02X" % b for b in blob[i:i + 24]) + ",\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("old_header")
    ap.add_argument("--fps", type=int, default=0, help="resample down to N fps")
    ap.add_argument("--out", default="src/video_data.h")
    ap.add_argument("--bin", default="", help="also dump the raw stream here")
    a = ap.parse_args()

    w, h, fps, frames, bpf, raw, old_size = parse_old_header(a.old_header)
    print("source: %dx%d  %d fps  %d frames  (%d B compressed)"
          % (w, h, fps, frames, old_size))

    if a.fps:
        raw, frames, fps = drop_fps(raw, bpf, frames, fps, a.fps)
        print("resampled to %d fps -> %d frames" % (fps, frames))

    blob = lzma.compress(raw, format=lzma.FORMAT_RAW, filters=FILTERS)
    print("raw stream:  %d B" % len(raw))
    print("compressed:  %d B  (%.1f%% of raw, %+d B vs old header)"
          % (len(blob), 100.0 * len(blob) / len(raw), len(blob) - old_size))

    write_header(a.out, w, h, fps, frames, bpf, blob)
    if a.bin:
        open(a.bin, "wb").write(blob)
    print("wrote %s" % a.out)


if __name__ == "__main__":
    main()
